name: au-journey-web-frontend
static_sites:
- name: web
  git:
    repo_clone_url: https://github.com/your-username/au-journey-web-frontend.git
    branch: main
  build_command: npm run build
  output_dir: /dist
  environment_slug: static-site
  envs:
  - key: VITE_BACKEND_URL
    value: https://au-journey-web-backend-gk6n3.ondigitalocean.app
  - key: VITE_APP_ENV
    value: production
